version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres-db
    networks:
      - instagram-influencers

  postgres-db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - instagram-influencers

networks:
  instagram-influencers:
    driver: bridge

volumes:
  postgres_data:
